name: Check Schema

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
    pull_request:

permissions:
  checks: write

jobs:
  test:
    name: Annotate Breaking Changes
    runs-on: ubuntu-latest
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: GraphQL Inspector
        uses: kamilkisiela/graphql-inspector@master
        with:
          schema: 'main:schema.graphql'
          approve-label: breaking